# Generated by Django 5.2 on 2025-04-20 12:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
